name = mc_parity
description = Extra Minecraft-style mobs for VoxeLibre/Mineclonia: full 1.0-1.21 parity (fox, panda, camel, skeleton horse, goat, allay, frog, warden, phantom, turtle, sniffer, armadillo, bee, drowned, bogged, breeze + structures/items)
depends = mcl_mobs
optional_depends = mcl_bamboo, mcl_mobitems, mcl_core, lightning, mcl_structures, mcl_sculk, mcl_deepslate, walkover, mcl_walkover, mcl_chests, mcl_potions, mesecons, mcl_jukebox, mcl_mud, mcl_doors, mcl_stairs, mcl_signs, mcl_fences
license = GPL-3.0-only
media_license = CC-BY-SA-4.0
